[package]
name = "tuwunel_synapse_admin"
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "mod.rs"
bench = false
crate-type = [
	"rlib",
#	"dylib",
]

[dependencies]
axum = { workspace = true, features = ["query"] }
axum-extra.workspace = true
futures.workspace = true
http.workspace = true
ruma.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tuwunel-core.workspace = true
tuwunel-service.workspace = true

[lints]
workspace = true
